### ISSUE TITLE
rerender more than once?

### ISSUE THREAD

**Issue by DaveStein** [mpeyper/react-hooks-testing-library#75] opened 2019-05-16 19:45 UTC
Hey, just started using this library and I see it's fairly new (only 2 tagged questions on SO and no dedicated room in Reactiflux). I guess there are 3 questions now because of me :) 

https://stackoverflow.com/questions/56175396/why-is-re-run-only-updating-props-one-time-with-react-hooks-testing-libary

I posted this question, assuming the props should update on each `rerender` call. However I'm not sure if it's supposed to do that and it's a bug, or it's not supposed to do that and the documentation should be clarified. Thanks for any guidance!

**Comment by mpeyper** [comment] 2019-05-16 20:36
This should be working. In wondering if it's the way we're setting the props and you passing a falsy value (although I though default params only work for `undefined`)

https://github.com/mpeyper/react-hooks-testing-library/blob/master/src/index.js#L98

Either way, this should work, so I'll take a closer look at what's going on for you.

**Comment by DaveStein** [comment] 2019-05-16 20:53
Thanks. Gotta head out soon, but will hopefully have a small repro repo for ya if you couldn't do it by tomorrow.

**Comment by DaveStein** [comment] 2019-05-16 20:54
One more thing - in reality I am passing 3 arguments instead of just one. I simplified the example cause I doubt the multi arguments would be cause, but wanted to call that out

**Comment by mpeyper** [comment] 2019-05-17 01:43
Multiple arguments as in:

```js
rerender(a, b, c)
```

??

This wont work as expected as only the first argument is passed through to the hook callback.  Usuaully you would pass an object with multiple keys and destructure it in the callback:

```js
const { rerender } = renderHook(({ a, b, c }) => useSomeHook(a, b, c))

rerender({ a: newA, b, c})
```

The reason for this is it's supposed to mimic the `props` of the wrapping component.  There are some work-in-progress docs that explain how to use it in a bit more detail [here](https://react-hooks-testing-library.netlify.com/usage/basic-hooks#props).  Feedback and PRs are welcome if it's unclear.

Let me know if that is the cause of the issue.

**Comment by DaveStein** [comment] 2019-05-17 14:05
This is it. 🤦‍♂ 

I will update my SO question to show I was using two variables and then link her as the answer. But I'll gladly mark your answer as the one if you wanna post there and grab the points.

A few things about the docs:

- I clearly missed the brackets in `rerender (function([newProps])) `
- If I saw those brackets I would have thought about using an array rather than an object and probably still got lost
- You might want a sample for using those options
- I actually use jsdoc + github page on repo for my libraries, way clearer than any of the syntax highlighting in a readme. I can't setup a github page in your repo but maybe I can get that working in a PR for you? If that's something you would want.

All things aside, thanks for quick response and this library :)

**Comment by mpeyper** [comment] 2019-05-20 22:00
Are you referring to the square brackets (`[`)? In my experience, they are commonly used to denote optional parameters in an API reference. I could be wrong though and happy to consider alternative syntax if you've got some.

I'm glad this solved your issue. I'll close this now, but feel free to submit a PR improving the documentation as there are definitely improvements that can be made.

**Closed by mpeyper** 2019-05-20 22:00 UTC
Labels: question
